# Site Settings
name: Transylvanian Geochemistry Research Group
title: Transylvanian Geochem RG
description: The website of the Transylvanian Geochemsitry Research Group, working on the origin and interaction of fluids in different geotectonic settings. 
tags:
  - science
  - fluid geochemistry
  - research group
  - Transylvania
  - carbon cycle
show_hero: true
menu:
  - title: Home
    url: /
  - title: Project
    url: /project
  - title: Team
    url: /staff
  - title: Collaborators
    url: /collaborators 
  - title: Field Work and Expeditions
    url: /expeditions
  - title: Media
    url: /media
  - title: The Science
    url: /scientists
  - title: Contact
    url: /contact
  
email: youremail@test.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id


# Social Media Settings
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.transylvaniangeochemistry.org" 
google_analytics: "G-WLWEDBWSZZ"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'docs/',
  'vendor/',
  'LICENSE',
  'CHANGELOG.md',
  'jekflix.gemspec',
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v1.0
