name: Transylvanian Geochemsitry Research Group
title: Transylvanian Geochem RG
description: The website of the Transylvanian Geochemsitry Research Group, working on the origin and interaction of fluids in different geotectonic settings. 
tags:
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  menu:
  - title: Home
    url: /
  - title: Project
    url: /project
  - title: Team
    url: /team
  - title: Expeditions
    url: /expeditions
  - title: Media
    url: /media
  - title: Scientists
    url: /scientists
  - title: Contact
    url: /contact
email: youremail@test.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
